### ISSUE TITLE
css recipe: full height cell borders with correct margins

### ISSUE THREAD

**Issue by Guria** [bvaughn/react-virtualized#107]
![](http://i.imgur.com/DyAaWur.png)

```css
.FlexTable__headerColumn
{
  border-right: 1px solid rgb(204, 204, 204);
}
.FlexTable__headerColumn,
.FlexTable__rowColumn
{
  margin: 0 5px;
  height: 100%;
}
.FlexTable__headerColumn:first-of-type,
.FlexTable__rowColumn:first-of-type {
  margin-left: 10px;
}
.FlexTable__headerColumn:last-of-type,
.FlexTable__rowColumn:last-of-type {
  margin-right: 0px;
}
```

Wonder if this rules except one about border should be default.
Also not sure if it breaking change.

**Comment by bvaughn** [comment]
I don't understand what you're asking/suggesting.

**Comment by Guria** [comment]
1 minute

**Comment by Guria** [comment]
### border with default styles
```css
.FlexTable__headerColumn
{
  border-right: 1px solid rgb(204, 204, 204);
}
```
![](http://i.imgur.com/pt2bQy6.png)

vs 

### border with overrides (see start post)
full height, better placement
![](http://i.imgur.com/2qmIb8w.png)

First of all I just share solution which can be documented.
Another suggestion is to make this default:
```js
.FlexTable__headerColumn,
.FlexTable__rowColumn
{
  margin: 0 5px;
  height: 100%;
}
.FlexTable__headerColumn:first-of-type,
.FlexTable__rowColumn:first-of-type {
  margin-left: 10px;
}
.FlexTable__headerColumn:last-of-type,
.FlexTable__rowColumn:last-of-type {
  margin-right: 0px;
}
```
