### ISSUE TITLE
Shaking scrollbar

### ISSUE THREAD

**Issue by bugstamp** [bvaughn/react-virtualized#1196]
I'm working on the project, where we have two components - one with the Table and Autosizer and another one is left hand side menu.  Currently I'm facing the obstacle with scrollbar shaking when I open side menu with css transition and shrinking the component with Table.
But when i click somewhere on the page everything works as it should.I'm confused.

Could somebody give me a piece of advice on how it can be solved. 

Here is the example: https://codesandbox.io/s/l7r4lyn45m.
Please open it in full size mode and click toggle button to see it.

**Comment by iTonyYo** [comment]
```scss
.ReactVirtualized__Grid,
.ReactVirtualized__List {
  &::-webkit-scrollbar {
    display: none;
  }
}
```

Maybe you can try this to hide scrollbar or something.
