### ISSUE TITLE
Grid: Request to add config option to use top/left positioning instead of CSS transform

### ISSUE THREAD

**Issue by jonaslundgren** [bvaughn/react-virtualized#122]
Transforms has one big drawback, it creates a new stacking context (https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context) making it very difficult to put child elements on top of other rendered cells (such as context menus). I've created an example demonstrating the issue here: http://codepen.io/anon/pen/grYLLy .

I'm willing to create a pull request with a fix if you would like :)

**Comment by bvaughn** [comment]
I'm a little confused by your Codepen. You're using the same class for the item you're trying to put below and above, so I'm not sure how that would work. If you modified your Codepen slightly, it works:

```html
<div>  
  <div class="menu" style="transform: translate(0px, 0px); background-color: red;">
    <div class="menu">
      <div>Attempting to put this on top</div>
    </div>
  </div>
  <div class="row" style="transform: translate(20px, 50px); background-color: blue">aa</div>
</div>
```

```css
.row {
  width: 120px;
  height: 120px;
  position: absolute;
}

.menu {
  z-index: 10; 
  position: absolute;
  background-color: green;
  height: 80px;
}
```

Renders like this:
<img width="149" alt="screen shot 2016-02-25 at 7 09 08 am" src="https://cloud.githubusercontent.com/assets/29597/13323519/b49b7be2-db8e-11e5-99fa-a21065611d20.png">

I've considered making the transform option configurable (see #94) but for different reasons. It should not be necessary to achieve what you're trying to do.
