### ISSUE TITLE
FlexTable does not work in IE9

### ISSUE THREAD

**Issue by 3cooper** [bvaughn/react-virtualized#244]
When in IE9, FlexTable only renders one column.  I'm not sure if FlexTable actually uses FlexBox.  If so, I guess this is the case and possibly not much can be done.  I heard there are some FlexBox polyfills, so possibly I could get those to work on my own.  I just wanted to check if this was the reason why.  I'm completely new to FlexBox so I'm not sure how to tell if FlexTable is actually using it.  Thanks for your time.

**Comment by bvaughn** [comment]
`FlexTable` does use flexbox (hence the name) which unfortunately means that it won't play nicely with most version of IE (see [caniuse](http://caniuse.com/#search=flexbox)).

I'm not sure of the best solution for this that wouldn't add burden to non-IE targets. Perhaps using `display: table` and `display: table-cell` fallbacks for IE? I don't know if this would work in all cases. It certainly wouldn't behave exactly like flexbox...

**Comment by bvaughn** [comment]
Maybe something like this... 

```css
.FlexTable .Grid__cell {
  display: table; /* Fallback for IE */
  display: block; /* Used by all other browsers */
}
.FlexTable__row {
  display: table-row; /* Fallback for IE */
  display: flex; /* Used by all other browsers */
}
.FlexTable__rowColumn {
  display: table-cell; /* Fallback for IE */
  display: flex; /* Used by all other browsers */
}
```

And then use the inline `style` (or `className`) properties of `FlexColumn` to set specific widths for your IE tables. So for instance, a flexbox column with a basis of 60px set to grow (eg `flex: 0 1 60px;`) would get an inline style of `width: 60px; min-width: 60px;`).
