### ISSUE TITLE
Outline of components

### ISSUE THREAD

**Issue by kirillku** [bvaughn/react-virtualized#782]
I have found that all the examples on the react-virtualized website have outline, when it focused. Is it expected behavior? 

I am disabling it my project by adding
```css
.ReactVirtualized__Grid {
  outline: none;
}
```

Should it be disabled in `react-virtualized/styles.css` the same way or there are more elegant way?
